// <auto-generated />
using System;
using AspNetTemplate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspNetTemplate.Migrations
{
    [DbContext(typeof(AppData))]
    partial class AppDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspNetTemplate.Core.Data.DbContexts.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("AspNetTemplate.Features.Auth.Data.AccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.HasIndex("UserId", "UserRole")
                        .HasDatabaseName("idx_access_tokens_user_active")
                        .HasFilter("\"IsRevoked\" = false");

                    b.ToTable("AccessTokens");
                });

            modelBuilder.Entity("AspNetTemplate.Features.Auth.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FileId");

                    b.HasIndex("IsAdmin")
                        .IsUnique()
                        .HasFilter("\"IsAdmin\" = TRUE");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasTrigger("LC_TRIGGER_AFTER_DELETE_USER");

                            t.HasTrigger("LC_TRIGGER_AFTER_INSERT_USER");

                            t.HasTrigger("LC_TRIGGER_AFTER_UPDATE_USER");
                        });

                    b
                        .HasAnnotation("LC_TRIGGER_AFTER_DELETE_USER", "CREATE FUNCTION \"LC_TRIGGER_AFTER_DELETE_USER\"() RETURNS trigger as $LC_TRIGGER_AFTER_DELETE_USER$\r\nBEGIN\r\n  \r\n  IF OLD.\"FileId\" IS NOT NULL THEN \r\n    UPDATE \"Files\"\r\n    SET \"UsageCount\" = \"Files\".\"UsageCount\" - 1\r\n    WHERE OLD.\"FileId\" = \"Files\".\"Id\";\r\n  END IF;\r\nRETURN OLD;\r\nEND;\r\n$LC_TRIGGER_AFTER_DELETE_USER$ LANGUAGE plpgsql;\r\nCREATE TRIGGER LC_TRIGGER_AFTER_DELETE_USER AFTER DELETE\r\nON \"Users\"\r\nFOR EACH ROW EXECUTE PROCEDURE \"LC_TRIGGER_AFTER_DELETE_USER\"();")
                        .HasAnnotation("LC_TRIGGER_AFTER_INSERT_USER", "CREATE FUNCTION \"LC_TRIGGER_AFTER_INSERT_USER\"() RETURNS trigger as $LC_TRIGGER_AFTER_INSERT_USER$\r\nBEGIN\r\n  \r\n  IF NEW.\"FileId\" IS NOT NULL THEN \r\n    UPDATE \"Files\"\r\n    SET \"UsageCount\" = \"Files\".\"UsageCount\" + 1\r\n    WHERE NEW.\"FileId\" = \"Files\".\"Id\";\r\n  END IF;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_AFTER_INSERT_USER$ LANGUAGE plpgsql;\r\nCREATE TRIGGER LC_TRIGGER_AFTER_INSERT_USER AFTER INSERT\r\nON \"Users\"\r\nFOR EACH ROW EXECUTE PROCEDURE \"LC_TRIGGER_AFTER_INSERT_USER\"();")
                        .HasAnnotation("LC_TRIGGER_AFTER_UPDATE_USER", "CREATE FUNCTION \"LC_TRIGGER_AFTER_UPDATE_USER\"() RETURNS trigger as $LC_TRIGGER_AFTER_UPDATE_USER$\r\nBEGIN\r\n  \r\n  IF OLD.\"FileId\" IS NOT NULL AND OLD.\"FileId\" <> NEW.\"FileId\" THEN \r\n    UPDATE \"Files\"\r\n    SET \"UsageCount\" = \"Files\".\"UsageCount\" - 1\r\n    WHERE OLD.\"FileId\" = \"Files\".\"Id\";\r\n  END IF;\r\n  \r\n  IF NEW.\"FileId\" IS NOT NULL AND OLD.\"FileId\" <> NEW.\"FileId\" THEN \r\n    UPDATE \"Files\"\r\n    SET \"UsageCount\" = \"Files\".\"UsageCount\" + 1\r\n    WHERE NEW.\"FileId\" = \"Files\".\"Id\";\r\n  END IF;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_AFTER_UPDATE_USER$ LANGUAGE plpgsql;\r\nCREATE TRIGGER LC_TRIGGER_AFTER_UPDATE_USER AFTER UPDATE\r\nON \"Users\"\r\nFOR EACH ROW EXECUTE PROCEDURE \"LC_TRIGGER_AFTER_UPDATE_USER\"();");
                });

            modelBuilder.Entity("AspNetTemplate.Features.Auth.Data.User", b =>
                {
                    b.HasOne("AspNetTemplate.Core.Data.DbContexts.UploadedFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId");

                    b.Navigation("File");
                });
#pragma warning restore 612, 618
        }
    }
}
